--
--Drop Table : 'has_catering'
--
DROP TABLE has_catering CASCADE CONSTRAINTS;

DROP TABLE Payments CASCADE CONSTRAINTS;

DROP TABLE Gusts CASCADE CONSTRAINTS;

DROP TABLE Catering CASCADE CONSTRAINTS;

DROP TABLE Customers CASCADE CONSTRAINTS;

DROP TABLE Venues CASCADE CONSTRAINTS;

DROP TABLE Events_ CASCADE CONSTRAINTS;

