--
--Drop Tables
--
DROP TABLE has_catering CASCADE CONSTRAINTS;

DROP TABLE Payments CASCADE CONSTRAINTS;

DROP TABLE Guests CASCADE CONSTRAINTS;

DROP TABLE Catering CASCADE CONSTRAINTS;

DROP TABLE Customers CASCADE CONSTRAINTS;

DROP TABLE Venues CASCADE CONSTRAINTS;

DROP TABLE Events_ CASCADE CONSTRAINTS;



--
--Drop GIVEN Tables
--


DROP TABLE PRODUCER CASCADE CONSTRAINTS;

DROP TABLE INSTRUMENT CASCADE CONSTRAINTS;

DROP TABLE INSTRUMENT_EVENT CASCADE CONSTRAINTS;

DROP TABLE SINGER CASCADE CONSTRAINTS;
